### ISSUE TITLE
Error running script

### ISSUE THREAD

**Issue by trbouma** [meshcollider/musig2-py#1]
Hi, I get this error when I try to run the script. Any ideas what the issue is? Thx

`python3 musig-2.py keygen
Traceback (most recent call last):
  File "musig-2.py", line 138, in <module>
    def write_bytes_list_to_hex(bytes_list: list[bytes], filename: str) -> bool:
TypeError: 'type' object is not subscriptable`

**Comment by meshcollider** [comment]
Have you modified the script somehow? That doesn't look right.

Firstly I notice the filename is wrong (`musig-2.py` not `musig2.py`).
Secondly keygen does not call `write_bytes_list_to_hex`, so that error doesn't make sense.

Everything runs fine for me on master.

**Comment by trbouma** [comment]
Thanks,
I just cloned the repo into repl.it here https://replit.com/@trbouma/musig2-py#.replit

In the shell, I tried running python3 musig2.py keygen
I got the same error:

`Traceback (most recent call last):
  File "musig2.py", line 138, in <module>
    def write_bytes_list_to_hex(bytes_list: list[bytes], filename: str) -> bool:
TypeError: 'type' object is not subscriptable`

You can replicate in the link above.

I am fairly new in this space, so I am probably missing something obvious. Thanks again, Tim

**Comment by meshcollider** [comment]
Ah, I see. Python v3.8 and below do not understand `list[bytes]`. I have pushed a change which should make this compatible with python 3.6+

Let me know if the issue isn't fixed and I'll reopen.

**Comment by trbouma** [comment]
@meshcollider  it all works now! Thanks!
